# Generated by Django 5.2.12 on 2026-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('session_count', models.IntegerField(default=0)),
                ('preference_stats', models.JSONField(default=dict)),
                ('activity_stats', models.JSONField(default=dict)),
                ('recent_queries', models.JSONField(default=list)),
                ('common_duration', models.IntegerField(blank=True, null=True)),
                ('last_activity_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='PoiEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='厦门', max_length=50)),
                ('gcj_lng', models.FloatField()),
                ('gcj_lat', models.FloatField()),
                ('wgs_lng', models.FloatField(blank=True, null=True)),
                ('wgs_lat', models.FloatField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=100)),
                ('poi_type', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'poi_entities',
                'indexes': [models.Index(fields=['city', 'poi_type'], name='poi_entitie_city_d3f240_idx'), models.Index(fields=['name'], name='poi_entitie_name_3d1678_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('user_query', models.TextField()),
                ('parsed_params', models.JSONField(default=dict)),
                ('origin_name', models.CharField(blank=True, max_length=200)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('route_result', models.JSONField(default=dict)),
                ('ai_response', models.TextField(blank=True)),
                ('total_time_s', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'route_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='route_histo_session_d74d0d_idx')],
            },
        ),
    ]
