# Generated by Django 5.2.12 on 2026-03-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KGNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('node_type', models.CharField(choices=[('海滩', '海滩'), ('公园', '公园'), ('学校', '学校'), ('景区', '景区'), ('体育', '体育场馆'), ('商业', '商业区'), ('交通', '交通枢纽'), ('山地', '山地'), ('湿地', '湿地')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('gcj_lng', models.FloatField(blank=True, null=True)),
                ('gcj_lat', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(default='厦门', max_length=50)),
                ('suitable_activities', models.JSONField(default=list)),
                ('surface_types', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kg_nodes',
                'indexes': [models.Index(fields=['city', 'node_type'], name='kg_nodes_city_d14e3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='KGEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('相邻', '地理相邻'), ('路线连接', '路线连接'), ('属于', '行政归属'), ('适合同行', '适合同一活动'), ('步行可达', '步行可达'), ('骑行可达', '骑行可达')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='route_planner.kgnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='route_planner.kgnode')),
            ],
            options={
                'db_table': 'kg_edges',
                'unique_together': {('source', 'target', 'relation')},
            },
        ),
    ]
